/**
 * Chinese aliases for carriers and airports.
 *
 * The archive stores English names ("Alaska Airlines Inc."), while users
 * naturally ask in Chinese ("阿拉斯加航空"). This table is the bridge; it only
 * covers entities that actually exist in the 2009-2018 BTS data set, and every
 * entry is a *code* reference — the authoritative name always comes from the
 * database via `getFilterOptions`.
 */

/** IATA code -> additional Chinese spellings. */
export const CARRIER_ALIASES: Record<string, string[]> = {
  UA: ['美联航', '联合航空', '美国联合航空'],
  DL: ['达美', '达美航空'],
  AA: ['美国航空', '美航'],
  WN: ['西南航空', '西南'],
  B6: ['捷蓝', '捷蓝航空'],
  AS: ['阿拉斯加航空', '阿拉斯加'],
  NK: ['精神航空', '精神'],
  F9: ['边疆航空', '边疆'],
  HA: ['夏威夷航空', '夏威夷'],
  G4: ['忠实航空', '忠实'],
  EV: ['快捷航空', '快捷喷气', 'expressjet'],
  OO: ['天西航空', '天西'],
  MQ: ['使者航空', '环境航空'],
  YX: ['共和航空', '中西部航空'],
  US: ['全美航空', '美国西部航空'],
  FL: ['穿越航空'],
  VX: ['维珍美国', '维珍美国航空'],
  WS: ['西捷航空'],
  AC: ['加拿大航空'],
  '9E': ['奋进航空', '英迪格航空'],
  OH: ['美国之鹰', 'psa航空'],
  F9X: [],
};

/** IATA code -> additional Chinese spellings for the busiest airports. */
export const AIRPORT_ALIASES: Record<string, string[]> = {
  ATL: ['亚特兰大', '哈茨菲尔德'],
  LAX: ['洛杉矶', '洛杉矶国际'],
  ORD: ['芝加哥', '奥黑尔'],
  DFW: ['达拉斯', '达拉斯沃斯堡', '沃斯堡'],
  DEN: ['丹佛'],
  JFK: ['肯尼迪', '纽约肯尼迪'],
  EWR: ['纽瓦克'],
  LGA: ['拉瓜迪亚'],
  SFO: ['旧金山', '圣弗朗西斯科'],
  SEA: ['西雅图', '塔科马'],
  LAS: ['拉斯维加斯', '麦卡伦'],
  PHX: ['凤凰城', '菲尼克斯'],
  MIA: ['迈阿密'],
  IAH: ['休斯顿', '休斯敦'],
  MCO: ['奥兰多'],
  CLT: ['夏洛特'],
  DTW: ['底特律'],
  MSP: ['明尼阿波利斯', '圣保罗'],
  PHL: ['费城'],
  SLC: ['盐湖城'],
  SAN: ['圣迭戈', '圣地亚哥'],
  BOS: ['波士顿'],
  IAD: ['杜勒斯', '华盛顿杜勒斯'],
  DCA: ['里根', '华盛顿里根'],
  BWI: ['巴尔的摩'],
  MDW: ['芝加哥中途', '中途机场'],
  HNL: ['檀香山', '火奴鲁鲁'],
  TPA: ['坦帕'],
  PDX: ['波特兰'],
  STL: ['圣路易斯'],
  AUS: ['奥斯汀'],
  BNA: ['纳什维尔'],
  MSY: ['新奥尔良'],
  RDU: ['罗利', '达勒姆'],
  CLE: ['克利夫兰'],
  PIT: ['匹兹堡'],
  CVG: ['辛辛那提'],
  MKE: ['密尔沃基'],
  CMH: ['哥伦布'],
  IND: ['印第安纳波利斯'],
  SMF: ['萨克拉门托'],
  SJC: ['圣何塞', '圣荷西'],
  OAK: ['奥克兰'],
  FLL: ['劳德代尔堡'],
  PBI: ['棕榈滩'],
  RSW: ['迈尔斯堡'],
  JAX: ['杰克逊维尔'],
  SAT: ['圣安东尼奥'],
  DAL: ['达拉斯爱田'],
  HOU: ['休斯顿霍比', '霍比'],
};

/** Legal-form words dropped before an entity name is turned into a token. */
export const NAME_STOPWORDS: ReadonlySet<string> = new Set([
  'inc',
  'inc.',
  'co',
  'co.',
  'corp',
  'corp.',
  'corporation',
  'llc',
  'ltd',
  'company',
  'holdings',
  'group',
  'the',
  'airlines',
  'airline',
  'airways',
  'air',
  'lines',
  'line',
  'system',
  'systems',
  'international',
  'intl',
  'regional',
  'municipal',
  'airport',
  'field',
  'county',
  'metropolitan',
  'authority',
  'and',
  'of',
  'de',
  'national',
  'memorial',
  'wold',
  'chamberlain',
  'san',
]);
